import React from 'react';
import { Link } from 'react-router-dom';
import { Layout, Breadcrumb } from 'antd';
//import Markdown from "markdown-to-jsx";

const { Content } = Layout; 

export default function BibliographyPage( props ) {
    return(
        <Layout>
            <Content style={{ marginLeft: "50px", marginTop: "20px" }}>
                <Breadcrumb>
                    <Breadcrumb.Item><Link to="/">Home</Link></Breadcrumb.Item>
                    <Breadcrumb.Item><Link to="/bibliographie">Bibliographie</Link></Breadcrumb.Item>
                </Breadcrumb>
            
                <Layout style={{ marginTop: "20px", marginBottom: "20px" }}>
                <div style={{ maxWidth: "800px", marginLeft: "100px", marginRight: "100px"}}>
                    <h1 style={{fontSize: "1.7rem"}}><a id="0"></a>Schriften über musikalische Preisausschreiben, 1820-1870</h1>
                    <h1 style={{fontSize: "1.7rem"}}><a id="2"></a>Bibliografie</h1>
                    <p id="line4">Die Bibliografie strebt an, alle Texte zu verzeichnen, die sich mit musikalischen Preisausschreiben befassen, im definierten Korpus vorkommen und nicht in der Datenbank bereits als Quelle genannt sind. Die Autorennamen wurden nicht angeglichen oder vervollständigt, sondern erscheinen wie in den Zeitschriften. Die Systematisierung soll die Orientierung erleichtern, stellt aber selbstverständlich nur eine mögliche Ordnung dar.</p>
                    <p id="line7"><b> Sinn und Zweck von Preisausschreiben </b></p>
                    <p id="line9">•   J. P. Schmidt, „Ueber den Nutzen musikalischer Preis-Aufgaben“, in: <em>Allgemeine musikalische Zeitung</em> 38/44 (2. November 1836), S. 717f.<br />
                        •   J. F., „Ueber den Nutzen musikalischer Preis-Aufgaben. Zu dem Aufsatze von J. P. Schmidt in No. 44“, in: <em>Allgemeine musikalische Zeitung</em> 38/46 (16. November 1836), S. 749f.<br />
                        •   G. W. Fink, „Gedanken über den vorigen Aufsatz und meine Meinung über musikalische Preisaufgaben“, in: <em>Allgemeine musikalische Zeitung</em> 38/46 (16. November 1836), S. 752-758.<br />
                        •   Sebald v. Walde, „Ueber musikalische Preisaufgaben“, in: <em>Neue Zeitschrift für Musik</em> 4/26 (31. März 1837), S. 104f. [Opernkompositionspreisausschreiben]<br />
                        •   LL., „Ueber die von der königl. Akademie in Berlin gekrönte Preiscomposition“, in: <em>Neue Zeitschrift für Musik</em> 7/2 (7. Juli 1837), S. 7f., 7/3 (11. Juli 1837), S. 10f.<br />
                        •   Miltitz, „Noch ein Wort über den Nutzen der musikalischen Preisaufgaben“, in: <em>Cäcilie, eine Zeitschrift für die musicalische Welt</em> 19/74 (1837), S. 131f. [Kritik zu Kompositionspreisausschreiben].<br />
                        •   K. Stein, „Noch ein Wort über musikalische Preisaufgaben“, in: <em>Cäcilie, eine Zeitschrift für die musicalische Welt</em> 19/75 (1837), S. 252f. [mit Bezug auf die Wiener Preissinfonie].<br />
                        •   Flodoard Geyer, „Ueber Preisbewerbungen. Mit besonderer Rücksicht auf die in Hechingen“, in: <em>Berliner Musikalische Zeitung</em> 3/28 (11. Juli 1846), S. [1-2].<br />
                        •   [Anon.], „Eine Preisrichter-Sitzung in Paris“, in: <em>Berliner Musikalische Zeitung</em> 3/31 (1. August 1846), S. [1-2].<br />
                        •   Henri Blanchard, „Mon livre ou souvenirs pour servir à l'histoire littéraire et musicale de la première moitié de ce siècle. (Troisième article.)“, in: <em>Revue et Gazette musicale de Paris</em> 15/44 (29. Oktober 1848), S. 336-338 [Kritischer Aufsatz zum allgemeinen Nutzen von Preisausschreiben, am Beispiel der Ausschreibungen französischer Nationallieder sowie dem Prix de Rome].<br />
                        •   A. Tschirch, „Feuilleton. Über einige Mittel, Compositionen jüngerer Tonkünstler in die Öffentlichkeit einzuführen“, in: <em>Neue Berliner Musikzeitung</em> 6/33 (18. August 1852), S. 261 [zu Vorzügen musikalischer Preisausschreiben].<br />
                        •   [Anon.], „Ueber Preisausschreiben für musikalische Kompositionen (I)“, in: <em>Süddeutsche Musikzeitung</em> 1/38 (20. Dezember 1852), S. 149f.<br />
                        •   [Anon.], „Ueber Preisausschreiben (Schluss)“, in: <em>Süddeutsche Musikzeitung</em> 1/39 (27. Dezember 1852), S. 154.<br />
                        •   F. P., „Cose teatrali di Torino“, in: <em>L'Italia musicale</em> 6/102 (23. Dezember 1854), S. 406f. [Wettbewerbe allgemein].<br />
                        •   [Anon.], „Der Musik-Verlag in Deutschland“, in: <em>Niederrheinische Musik-Zeitung</em> 4/10 (15. März 1856), S. 81f. [u. a. auch darüber, dass Kompositionspreisausschreiben das allgemeine Niveau musikalischer Kompositionen nicht heben würden].<br />
                        •   F. Brendel, „Statuten des Allgemeinen deutschen Musikvereins“, in: <em>Neue Zeitschrift für Musik</em> 53/11 (7. September 1860), S. 89f. [Kompositionspreisausschreiben hätten sich als weniger sinnvoll und ergiebig herausgestellt als musikhistorische Preisausschreiben.].<br />
                        •   [Anon.], „Society for the Encouragement of the Fine Arts“, in: <em>The Musical World</em> 38/1 (7. Januar 1860), S. 5-7 [Berichterstattung über die Vollversammlung der „Society for the Encouragement of the Fine Arts“: Wiedergabe der Diskussion über Preisausschreiben in den Künsten im Allgemeinen sowie in der Musik im Speziellen].<br />
                        •   Alex T. Teetjen, „Prize for Stringed Quartets“, in: <em>The Musical World</em> 40/48 (29. November 1862), S. 765 [Wunsch nach einem Kompositionspreisausschreiben].<br />
                        •   Otto Beard, „o. T. Titel“, in: <em>The Musical World</em> 42/17 (23. Mai 1864), S. 264f. [Kritik an einem geplanten Preisausschreiben des neugegründeten College of Organists. Die Kritik enthält eine detaillierte Abhandlung über die Gestaltung von Preisausschreiben allgemein.].<br />
                        •   [Anon.], „Ueber Preis-Aufgaben“, in: <em>Neue Berliner Musikzeitung</em> 20/28 (11. Juli 1866), S. 219f.<br />
                        •   G. Roores, „o. T.“, in: <em>The Musical World</em> 44/29 (21. Juli 1866), S. 459f. [zu musikalischen Preisausschreiben und ihren Nutzen für MusikerInnen allgemein].<br />
                        •   [Anon.], „Gesang und Oper“, in: <em>Niederrheinische Musik-Zeitung</em> 15/22 (1. Juni 1867), S. 169f. [Ablehnung von Preissingen].<br />
                        •   P. Lacome, „Trop de concours“, in: <em>Revue et Gazette musicale de Paris</em> 37/10 (6. März 1870), S. 73-74 [Aufsatz zum Nutzen von Kompositionspreisausschreiben als Kommentar zu einem veröffentlichten Brief von Amaury Duval. Plädoyer, Preisausschreiben durch das Prinzip der Ausstellung aus der bildenden Kunst zu ersetzen, bei dem die Öffentlichkeit urteilt.].</p>
                    <p id="line34"><b> Werturteile und ihre Probleme </b></p>
                    <p id="line36">•   Fétis, „Nouvelles de Paris. Institut de France. Séance publique annuelle de l'Académie Royale des Beaux-Arts, (samedi 6 octobre.)“, in: <em>Revue Musicale</em> 1/[35] ([Oktober] 1827), S. 253-260 [inkl. genereller Problematisierung der Beurteilung durch Jurys].<br />
                        •   [Anon.], [o.T.], in: <em>Revue Musicale</em> 4/[1] (1828), S. 18-20 [zum Nutzen von Musikwettbewerben allgemein sowie im Besonderen im Militär].<br />
                        •   [Anon.], „Rhapsodien“, in: <em>Neue Zeitschrift für Musik</em> 1/33 (24. Juli 1834), S. 130 [über das Vergleichen und Bewerten in der Kunst].<br />
                        •   Fétis père, „Que peut-on faire pour améliorer la condition des jeunes compositeurs et pour Porter remède à la décadence de la musique? (5e et dernier article) (1)“, in: <em>Revue et Gazette musicale de Paris</em> 25/13 (28. März 1858), S. 101-103 [Aufruf an Jurymitglieder von Kompositionswettbewerben, die sich an den Nachwuchs richten, zur Strenge der Bewertung].<br />
                        •   [Anon.], „o. T.“, in: <em>The Musical World</em> 39/15 (13. April 1861), S. 232f. [Vergleich von Werturteilen in Musik und Bildender Kunst].<br />
                        •   [Anon.], „Society for the Encouragement of the Fine Arts“, in: <em>The Musical World</em> 40/11 (15. März 1862), S. 165 [zur Society, die Preise in den verschiedenen Künsten vergibt und zu den Problemen bei der Verteilung der Musikpreise].<br />
                        •   B. Congreve, „Prize Competitions“, in: <em>The Musical World</em> 47/8 (20. Februar 1869), S. 119 [Autor plädiert dafür, das Ranking der TeilnehmerInnen eines Preisausschreibens zu veröffentlichen, anstatt nur die SiegerInnen bekannt zu geben.].</p>
                    <p id="line45"><b>Forderungen, Wünsche, Ideen</b></p>
                    <p id="line47">•   [Anon.], „Nouvelles de Paris“, in: <em>Revue Musicale</em> 8/46 (16. November 1834), S. 365-366 [Vorschlag zu einem französischen Verbund zwischen der Athénée musicale de Paris und Musikgesellschaften der Départements, dessen Zweck neben Aufführungen und der Herausgabe einer Zeitschrift ein jährlicher Kompositionswettbewerb sein solle].<br />
                        •   F. Liszt, „De la situation des artistes, et de leur condition dans la société. (Dernier article.)“, in: <em>Gazette musicale de Paris</em> 2/41 (11. Oktober 1835), S. 332f. [Utopie einer „société universelle“ aller Musiker, die als erste Maßnahme alle fünf Jahre einen Kompositionswettbewerb – siehe Übersetzung als „Wettbewerb“ in Kleinertz (Hg.), <em>Frühe Schriften (2000)</em>, S. 63 – abhalten soll, bei dem die besten religiösen, dramatischen und sinfonischen Werke feierlich im Louvre aufgeführt und dann auf Kosten der Regierung veröffentlicht werden sollen].<br />
                        •   [Anon.], „Musical Art-Unions“, in: <em>Saroni’s Musical Times</em> I 23 (2. März 1850), S. 266 [zur Gründung der Musical Art-Union mit der Empfehlung, Preise auszuschreiben].<br />
                        •   G. Bénédit, „De la décentralisation artistique“, in: <em>Revue et Gazette musicale de Paris</em> 17/32 (11. August 1850), S. 267-268 [Aufsatz, der u. a. das Thema der Nachwuchsförderung durch Kompositionspreise und die mangelnden Chancen der Preisträger an den Pariser Opernbühnen berührt, sowie außerdem den Vorschlag jährlicher, in allen französischen Städten stattfindender Preisausschreiben für Opernlibretti unterbreitet].<br />
                        •   L.D., „Vorschlag“, in: <em>Süddeutsche Musikzeitung</em> 1/10 (7. Juni 1852), S. 37 [Vorschlag für ein Preisausschreiben zur Musiktheorie].<br />
                        •   Ernest Lépine, „Projet. Audition périodique des œuvres des artistes vivants. Réponse aux réclamations de la Société Sainte-Cécile et de la Société des Jeunes-Artistes“, in: <em>Le Ménestrel</em> 22/7 (14. Januar 1855), S. 2f. [Bekräftigung der Idee eines nationalen Musikwettbewerbs].<br />
                        •   X., „Anregung zu einem allgemein deutschen Sänger-Concurs“, in: <em>Niederrheinische Musik-Zeitung</em> 6/31 (31. Juli 1858), S. 243f. [Ideen zu einem Gesangswettbewerb für SolistInnen].<br />
                        •   [Anon.], „‘Antigone’ at the Crystal Palace”, in: <em>The Musical Standard</em> 2/28 (15. September 1863), S. 53 [Wunsch nach einem musikalischen Preisausschreiben, an dem nur Engländer teilnehmen dürfen].<br />
                        •   [„Rusticus“], „Musical prizes. To the Editor of The Musical World“, in: <em>The Musical World</em> 41/15 (11. April 1863), S. 231 [Wunsch nach einem Kompositionspreisausschreiben].<br />
                        •   Roberts, Valentine, „Musical Prizes. To the Editor of the Musical World“, in: <em>The Musical World</em> 41/16 (18. April 1863), S. 246 [Wunsch nach einem Kompositionspreisausschreiben].<br />
                        •   [„Musicus“], „Musical Prizes. To the Editor of The Musical World“, in: <em>The Musical World</em> 41/17 (25. April 1863), S. 262 [Wunsch nach einem Kompositionspreisausschreiben].<br />
                        •   [„Ragd. A. Mus.“], „Pools. To the Editor of The Musical World“, in: <em>The Musical World</em> 41/18 (2. Mai 1863), S. 278 [Vorschlag für eine Lotterie musikalischer Preisausschreiben].<br />
                        •   [„A Professor“], „Musical Prizes. To the Editor of The Musical World“, in: <em>The Musical World</em> 41/23 (6. Juni 1863), S. 359 [Wunsch nach einem Kompositionspreisausschreiben].<br />
                        •   E. l'Épine, „Audition périodiques des œuvres musicales des artistes vivants“, in: <em>Le Ménestrel</em> 30/46 (18. Oktober 1863), S. 368 [Überarbeiteter Vorschlag eines staatlichen Kompositionswettbewerbs für eine aus 14 Konzerten bestehende große „audition“ von Vokal- und Instrumentalmusik].<br />
                        •   Paul Smith, „Projet d'auditions périodiques. D'oeuvres musicales d'artistes viants“, in: <em>Revue et Gazette musicale de Paris</em> 30/45 (8. November 1863), S. 355-356 [Kommentar u. a. zu den von Fétis geforderten regelmäßigen (staatlich subventionierten) Preisausschreiben für Opernlibretti und -partituren sowie zum Prix de Rome].<br />
                        •   Enderby Jackson, „Letters to the Editor“, in: <em>The Musical World</em> 42/2 (9. Januar 1864), S. 29 [Vorschlag für einen großen Musikwettbewerb zwischen Frankreich und England].<br />
                        •   [Anon.], „To the Editor of The Orchestra“, in: <em>The Orchestra</em> 3/64 (17. Dezember 1864), S. 188 [Leserbrief mit Wunsch zur Preisvergabe an Sänger].<br />
                        •   [Anon.], „A New Object for a Prize“, in: <em>The Musical Standard</em> 5/107 (18. August 1866), S. 102 [Leserbrief mit Wunsch nach einem Preisausschreiben für eine Kammerorgel].</p>
                    <p id="line67"><b>Ankündigungen und Pläne</b></p>
                    <p id="line69">•   Eduard Freiherr von Lannoy u.a., „Aufforderung an die Herren Componisten“, in: <em>Neue Zeitschrift für Musik</em> 26/31 (16. April 1847), S. 134 [Ankündigung, dass die Concert Spirituels nun jährlich eine Komposition ausschreiben].<br />
                        •   Ernest l'Épine, „Projet. Auditions musicales d'œuvres des artistes vivants“, in: <em>Le Ménestrel</em> 22/3 (17. Dezember 1854), S. 3f. [Entwurf eines von der französischen Regierung ausgeschriebenen, breit angelegten jährlichen Kompositionswettbewerbs für Vokal- und Instrumentalmusik analog zur staatlichen Förderung der bildenden Künste (gemeint war vermutlich der Salon de peinture et de sculpture); Vorschlag zum Auftakt bei der Pariser Weltausstellung 1855 die Musik gleichberechtigt neben den anderen Künsten teilhaben zu lassen; notwendige „audition“ analog zur „exposition“].<br />
                        •   [Anon.], „Tages- und Unterhaltungsblatt“, in: <em>Niederrheinische Musik-Zeitung</em> 10/15 (12. April 1862), S. 120 [Planung österreichischer Staatsstipendien für KünsterInnen].<br />
                        •   [Anon.], „Royal Academy of Music“, in: <em>The Musical World</em> 47/21 (22. Mai 1869), S. 359, 47/24 (12. Juni 1869), S. 418 [In Gedenken an den verstorbenen Charles Lucas soll an der Royal Academy of Music jährlich eine Goldmedaille für Komposition verliehen werden.].</p>
                    <p id="line75"><b>Beschwerden, Klagen und Scherze</b></p>
                    <p id="line77">•   [Anon.], „Novitäten“, in: <em>Signale für die musikalische Welt</em> 2/9 (März 1844), S. 69 [Witz über Preisausschreiben].<br />
                        •   Anon.], „Ueber Preisaufgaben“, in: <em>Neue Zeitschrift für Musik</em> 35/5 (1. August 1851), S. 48 [Beschwerde über den Umgang Ferdinand Hillers mit den nicht-ausgezeichneten Konkurrenten eines Kölner Kompositionspreisausschreibens].<br />
                        •   [Anon.], „Literatur“, in: <em>Süddeutsche Musikzeitung</em> 12/35 (31. August 1863), S. 137 [Auszug aus einem Brief Felix Mendelssohn-Bartholdys an seine Mutter, in dem er erklärt und begründet, nie wieder Jurymitglied bei einem musikalischen Preisausschreiben sein zu wollen].<br />
                        •   [Anon.], „Alla onorevole Commissione esaminatrice dei Concorsi“, in: <em>Gazzetta musicale di Milano</em> 23/10 (8. März 1868), S. 75f. [Leserbrief (Beschwerde) eines nicht-preisgekürten Teilnehmers eines Preisausschreibens der „Società del Quartetto di Milano“].</p>
                    <p id="line83"><b>Übersichten</b></p>
                    <p id="line85">•   [Anon.], „Nachrichten“, in: <em>Süddeutsche Musikzeitung</em> 14/14 (3. April 1865), S. 56 [Anzahl von Gesangvereinen, Musikvereinen, Musikfesten und Wettbewerben in Frankreich 1865].<br />
                        •   W., „Les concours de musique en Belgique“, in: <em>Le Guide musical</em> 11/16 (20. Mai 1865), S. 65 [Musikwettbewerbe in Belgien].<br />
                        •   [Anon.], „The One-Eyed Perch in Paris“, in: <em>The Orchestra</em> 7/180 (9. März 1867), S. 378f. [zu Preisausschreiben in Frankreich].</p>
                    <p id="line90"><b>Prix de Rome</b></p>
                    <p id="line92">•   [Anon.], „Correspondance“, in: <em>Revue Musicale</em> 1/1 (Februar 1827), S. 44-47 [Anonymer Brief eines „pauvre musicien“ mit Kritik an den mangelnden Karrierechancen im Opernbetrieb für Rompreisträger].<br />
                        •   Stéphen, „Projet d'Association Musicale. Société du Gymnase lyrique“, in: <em>Revue Musicale</em> 4/[13] ([Oktober] 1828), S. 289-296 [Versprechen von Aufführungsmöglichkeiten für die Rompreisträger in der gegründeten Konzertreihe Gymnase lyrique].<br />
                        •   Fétis, „De la commission pour la réorganisation des théâtres, de sa mission, et de l'importance de ses travaux“, in: <em>Revue Musicale</em> 9/[4] (4. September 1830), S. 97-111 [zu den Komplikationen bei der Umsetzung eines königlichen Erlasses, der die Académie des Beaux-Arts dazu verpflichtete, den Rompreisträgern bei ihrer Rückkehr nach Paris ein Libretto zu Verfügung zu stellen, sowie die Opéra, deren Opern aufzuführen].<br />
                        •   [Anon.], „Pétition présentée au ministre de l'intérieur par les artistes de Paris“, in: <em>Revue Musicale</em> 9/[4] (4. September 1830), S. 112-117 [Forderungen einer Musikerkommission nach Liberalisierung des Musikbetriebs, u.a. vereinfachtem Zugang zu den Opernbühnen für die Rompreisträger und einer ausschließlich durch Musikkenner besetzten Jury des Prix de Rome].<br />
                        •   [Anon.], „Nouvelles de Paris. Théâtre de l'Opéra-comique. Le grand prix, ou le voyage à frais communs [...]“, in: <em>Revue Musicale</em> 5/24 (16. Juli 1831), S. 190-192 [Rezension einer Opéra-comique, deren Handlung auf die Italienreisen der Rompreisträger Bezug nimmt].<br />
                        •   [Anon.], „Nouvelles de Paris“, in: <em>Revue Musicale</em> 6/47 (22. Dezember 1832), S. 375 [Nachricht über Gratiseintritt in die Opéra, den der Direktor Véron Zweitplatzierten des Rompreises gewähren wolle].<br />
                        •   H. Berlioz, „Institut. Concours de musique et voyage d'Italie du lauréat“, in: <em>Gazette musicale de Paris</em> 1/5 (2. Februar 1834), S. 35f. [satirischer Aufsatz zum Rompreis und der Italienreise].<br />
                        •   [Anon.], „Correspondenz“, in: <em>Neue Zeitschrift für Musik</em> 1/33 (24. Juli 1834), S. 132 [Prix de Rome: allgemeiner Ablauf].<br />
                        •   Germanus le Pic, „De l'éducation de compositeurs de musique. (Suite et fin.)“, in: <em>Gazette musicale de Paris</em> 2/43 (25. Oktober 1835), S. 348f.<br />
                        •   Hector Berlioz, „Concours annuel de composition musicale à l'Institut“, in: <em>Revue et Gazette musicale de Paris</em> 3/25 (19. Juni 1836), S. 203f.<br />
                        •   Germanus Le Pic, „Du concours pour le grand prix de musique, et du voyage des musiciens lauréats“, in: <em>Revue et Gazette musicale de Paris</em> 3/41 (9. Oktober 1836), S. 353f.<br />
                        •   Hector Berlioz, „Encore un mot sur le concours de composition musicale à l'Institut, en réponse au dernier article de M. Germanus Lepic“, in: <em>Revue et Gazette musicale de Paris</em> 3/43 (23. Oktober 1836), S. 370f.<br />
                        •   [Anon.], „French Encouragement of young Musicians“, in: <em>The Musical World</em> 3/33 (28. Oktober 1836), S. 101-103.<br />
                        •   H. Berlioz, „Théatre de l'Opéra-Comique. Première représentation de la Dame-d'Honneur, poëme de MM. E. Monnais et Paul Duport, musique de M. Despéraux“, in: <em>Revue et Gazette musicale de Paris</em> 5/40 (7. Oktober 1838), S. 397f.<br />
                        •   T., „Conservatoire de musique. Quelques mots sur le système d'enseignement suivi dans les classes de composition idéale“, in: <em>Revue musicale, journal des artistes, des amateurs et des théâtres</em> 6/23 (6. Juni 1839), S. 181f.<br />
                        •   Francis Wey, „Les dangers du Prix de Rome“, in: <em>La France musicale</em> 4/14 (4. April 1841), S. 116f. [zur Karriere eines Prix de Rome-Preisträgers].<br />
                        •   Hippolyte Prévost, „Quelques réflexions“, in: <em>La France musicale</em> 4/42 (17. Oktober 1841), S. 359f.<br />
                        •   Edmond Viel, „Les pensionnaires de Rome“, in: <em>Le Ménestrel</em> 8/46 (17. Oktober 1841 / 24. Oktober 1841), o. S. [Aufsatz mit kritischer Stellungnahme zur Pension des Prix de Rome und des damit verbundenen Auslandaufenthaltes in Italien].<br />
                        •   Paul Smith, „Dix années lyriques en France. (Quatrième et dernier article.)“, in: <em>Revue et Gazette musicale de Paris</em> 9/44 (30. Oktober 1842), S. 425f.<br />
                        •   [Anon.], „Notizie musicale varie“, in: <em>Gazzetta musicale di Milano</em> 3/23 (9. Juni 1844), S. 95<br />
                        •   A. Elwart, „De la position des jeunes compositeurs français. (Premier article.)“, in: <em>Revue et Gazette musicale</em> 13/18 (3. Mai 1846), S. 141f.<br />
                        •   A. Elwart, „De la position des jeunes compositeurs français. (Suite et fin.)“, in: <em>Revue et Gazette musicale</em> 13/20 (17. Mai 1846), S. 154f.<br />
                        •   J. Martin d'Angers, „De la musique sacrée“, in: <em>Revue et Gazette musicale</em> 13/25 (21. Juni 1846), S. 193f.<br />
                        •   Edouard Fétis, „Revue d'un demi-siècle. L'Opéra-comique de 1815 à 1830“, in: <em>Revue et Gazette musicale de Paris</em> 17/45 (10. November 1850), S. 371-374 [Aufsatz u. a. über den Erfolg der Rompreisträger als Komponisten der Opéra-comique].<br />
                        •   Edouard Fétis, „Revue d'un demi-siècle. L'Opéra-Comique de 1830 à 1850“, in: <em>Revue et Gazette musicale de Paris</em> 17/46 (17. November 1850), S. 377-381 [Aufsatz u.a. über den Erfolg der Rompreisträger als Komponisten der Opéra-comique].<br />
                        •   Aug. Gathy, „Die Pariser Prämianten und ihre Geschicke“, in: <em>Neue Zeitschrift für Musik</em> 34/17 (25. April 1851), S. 178f. [Prix de Rome: Karrieren der Preisträger]<br />
                        •   [Anon.], „Die Pariser Prämianten und ihre Geschicke“, in: <em>Neue Zeitschrift für Musik</em> 34/19 (9. Mai 1851), S. 195f. [Prix de Rome: Ablauf].<br />
                        •   [Anon.], „French Encouragement of Young Musicians“, in: <em>Dwight’s Journal of Music</em> 2/24 (19. März 1853), S. 187 [Kritischer Bericht zum Prix de Rome, in dem der Journalist die Urteilsfindung der Jury sowie die Leistungen während der Romreise kritisiert].<br />
                        •   Fétis père, „Que peut-on faire pour améliorer la condition des jeunes compositeurs et pour Porter remède à la décadence de la musique! (Premier article.)“, in: <em>Revue et Gazette musicale de Paris</em> 25/4 (24. Januar 1858), S. 25-27 [Kritik an den Auslandsreisen des französischen sowie belgischen Rompreises sowie am Mangel an Karrierechancen im Opernbetrieb bei der Rückkehr der Preisträger; Aufforderung zur Reform des Preises].<br />
                        •   [Anon.], „Die Ausbildung und Unterstützung junger Musiker“, in: <em>Süddeutsche Musikzeitung</em> 7/33 (16. August 1858), S. 129f. [zur Musikerausbildung, u. a. auch zu Preisausschreiben (Prix de Rome) und Stipendien].<br />
                        •   Ralph, „Prix de Rome“, in: <em>L'Art musical</em> 2/10 (6. Februar 1862), S. 73f. [sehr ausführlicher Bericht über den Prix de Rome allgemein].<br />
                        •   A. Suttner, „Musikalische Skizzen aus Paris“, in: <em>Signale für die musikalische Welt</em> 21/30 (25. Juni 1863), S. 481f.<br />
                        •   [Anon.], „France“, in Le Guide musical 10/20 (12. Mai 1864), S. 79 [neue Regularien zum Prix de Rome].<br />
                        •   Vaillant / Napoleon, „Rapport à l'Empereur“, in: <em>L'Art musical</em> 4/24 (12. Mai 1864), S. 190 [Bericht der Académie des Beaux-Arts an König Napoleon III. zu Änderungen der Organisation des Prix de Rome und Dekret Napoleons III.].<br />
                        •   Gustave Bertrand, „Semaine théâtrale“, in: <em>Le Ménestrel</em> 31/24 (15. Mai 1864), S. 187f. [Rom-Aufenthalt der Rompreisträger; deren Aufführungsmöglichkeiten in Paris; Reform des Rompreises].<br />
                        •   Ralph, „Les prix de Rome“, in: <em>L'Art musical</em> 4/49 (3. November 1864), S. 397f.<br />
                        •   Ralph, „Encore les prix de Rome“, in: <em>L'Art musical</em> 4/51 (17. November 1864), S. 411f.<br />
                        •   Gustave Bertrand, „Semaine théâtrale“, in: <em>Le Ménestrel</em> 34/19 (7. April 1867), S. 146f. [Kritische Stellungnahme zum Rom-Aufenthalt der Rompreisträger, den mangelnden Aufführungsmöglichkeiten in Paris und den Verpflichtungen der Opéra-comique und des Théâtre-lyrique zur Aufführung ihrer Stücke].<br />
                        •   Albert Vizentini, „Courrier musical“, in: <em>L'Art musical</em> 7/32 (11. Juli 1867), S. 253f. [zur Orphéons-Bewegung in Frankreich sowie dem Prix de Rome allgemein].<br />
                        •   Albéric Second, „Miséres d'un prix de Rome“, in: <em>Le Ménestrel</em> 35/30 (21. Juni 1868), S. 235f. [Abdruck von Auszügen aus dem gleichnamigen komischen Roman von Albéric Second mit kurzer einleitender Bemerkung].<br />
                        •   Gustave Bertrand, „Semaine théâtrale“, in: <em>Le Ménestrel</em> 35/30 (21. Juni 1868), S. 235 [Besprechung des komischen Romans „Misères d'un Prix de Rome“ von Albéric Second und dessen Topos der mangelnden Chancen der aus Italien nach Paris zurückkehrenden Rompreisträger zu Auftritten und Veröffentlichungen].<br />
                        •   Em. Mathieu de Monter, „Bibliographie musicale. Misères d'un prix de Rome, Par Albéric Second“, in: <em>Revue et Gazette musicale de Paris</em> 35/30 (26. Juli 1868), S. 235f. [Rezension des satirischen Romans von Second].<br />
                        •   Jules Ruelle, „France“, in: <em>Le Guide musical</em> 15/1 (7. Januar 1869), S. 6 [über den Prix de Rome, der sich im Niedergang befinden würde].<br />
                        •   A. A., „Carteggi“, in: <em>Gazzetta musicale di Milano</em> 24/4 (24. Januar 1869), S. 29f.<br />
                        •   Th. De Lajarte, „Cantates et Prix de Rome“, in: <em>La France musicale</em> 33/4 (24. Januar 1869), S. 25f.<br />
                        •   Gustave Chouquet, „Poètes et musiciens“, in: <em>L'Art musical</em> 9/14 (4. März 1869), S. 105f. [zum Prix de Rome allgemein].<br />
                        •   Mathieu de Monter, „Études biographiques et critiques“, in: <em>Revue et gazette musicale de Paris</em> 36/32 (8. August 1869), S. 258f., 36/33 (15. August 1869), S. 265f. [Hector Berlioz und der Prix de Rome].<br />
                        •   Ralph, „Le couteau à Janot“, in: <em>L'Art musical</em> 9/39 (26. August 1869), S. 317f. [Satire auf den Prix de Rome].<br />
                        •   Jules Ruelle, „France“, in: <em>Le Guide musical</em> 16/9 (3. März 1870), S. 69 [Teilnahme am Prix de Rome bis zum 30. Lebensjahr].<br />
                        •   [Anon.], „Faits divers“, in: <em>L'Art musical</em> 10/17 (24. März 1870), S. 134 [neue Teilnahmeregelungen für den Prix de Rome],<br />
                        •   A. v. Cz., „Correspondenzen“, in: <em>Neue Berliner Musikzeitung</em> 24/13 (30. März 1870), S. 101 [Altersbeschränkung für die Teilnahme am Prix de Rome von 15-25 Jahren auf 15-30 Jahren erweitert].<br />
                        •   Gustave Bertrand, „Semaine théâtrale. La question du prix de Rome“, in: <em>Le Ménestrel</em> 37/33 (17. Juli 1870), S. 259f. [Vorschlag erneuter Reform des Prix de Rome bezüglich Juryzusammensetzung, Aufgabenstellung und Aufführung vor der Jury].<br />
                        •   Fétis père, „Que peut-on faire pour améliorer la condition des jeunes compositeurs et pour Porter remède à la décadence de la musique! (Premier article.)“, in: <em>Revue et Gazette musicale de Paris</em> 25/4 (24. Januar 1858), S. 25-27 [Kritik an den Auslandsreisen des französischen sowie belgischen Rompreises sowie am Mangel an Karrierechancen im Opernbetrieb bei der Rückkehr der Preisträger; Aufforderung zur Reform des Preises].</p>
                    <p id="line147"><b>Prix de Rome Belge</b></p>
                    <p id="line149">•   [Anon.], „Correspondance“, in: <em>Revue et Gazette musicale de Paris</em> 21/43 (22. Oktober 1854), S. 345f. [zur öffentlichen Diskussion zwischen Ministerium um Académie de Belgique über die Karrierechancen der belgischen Rompreisträger als Komponisten im Opernbetrieb].<br />
                        •   Adolphe Samuel, „Le Conservatoire royale de Musique“, in: <em>Le Guide musical</em> 4/34 (21. Oktober 1858), S. 1 [allgemein über den Prix de Rome Belge].<br />
                        •   [Anon.], „Belgique“, in: <em>Le Guide musical</em> 13/23 (6./13. Juni 1867), S. 181 [Klage, dass die Preisträger des Prix de Rome Belge sich nicht an die mit Erhalt des Stipendiums verbundenen Auflagen halten würden].<br />
                        •   [Anon.], „Belgique“, in: <em>Le Guide musical</em> 13/31 /1./8. August 1867), S. 213 [Überlegungen zur Reform des Prix de Rome Belge].<br />
                        •   [Anon.], „Belgique“, in: <em>Le Guide musical</em> 15/31 (5./12. August 1869), S. 211 [Es kommt vor, dass die Preisträger nicht, wie es vorgesehen ist, mit dem Stipendium durch Europa reisen, sondern in Belgien bleiben. Neue Regularien sollen dem entgegenwirken.].</p>
                    <p id="line156"><b>Chorgesang / Glees</b></p>
                    <p id="line158">•   Th., „Aus London“, in: <em>Neue Zeitschrift für Musik</em> 3/40 (17. November 1835), S. 160 [Londoner „Glee-Club“, „Madrigal-Club", „Melodists-Club“ und deren jährliche Preisausschreiben für Vokalkompositionen].<br />
                        •   [Anon.], „Distribution of prizes by musical clubs“, in: <em>The Musical World</em> 10/137 (25. Oktober 1838), S. 120f. [allgemeine Kritik zu musikalischen Preisausschreiben (Fokus auf Glee Clubs)].<br />
                        •   [Anon.], „The Liverpool Beefsteak Club. To the Editor of the Musical World“, in: <em>The Musical World</em> 6/108 (23. Januar 1840), S. 55f. [Ausführliche Kritik der Wertungsinstanzen beim Preisausschreiben des Beef Steak Club].<br />
                        •   [Anon.], „The Liverpool Beefsteak Club. To the Editor of the Musical World“, in: <em>The Musical World</em> 6/109 (30. Januar 1840), S. 71f. [Leserbrief zur Kritik der Wertungsinstanzen beim Preisausschreiben des Beef Steak Club].<br />
                        •   [Anon.], „The Liverpool Beef Steak-Club, To the Editor of the Musical World“, in: <em>The Musical World</em> 6/111 (13. Februar 1840), S. 61f. [Leserbrief zur Kritik der Wertungsinstanzen beim Preisausschreiben des Beef Steak Club].<br />
                        •   [Anon.], „Mr. Gauntlett’s Prize Anthem. To the Editor of the Musical World“, in: <em>The Musical World</em> 8/165 (25. Februar 1841), S. 121 [Leserbrief zur Kritik der Wertungsinstanzen beim Preisausschreiben des Beef Steak Club].<br />
                        •   Sylvain Saint-Étienne, „De l'état de la musique en province. (Quatrième article)“, in: <em>Revue et Gazette musicale</em> 13/44 (1. November 1846), S. 345-348 [Aufsatz über französische Gesangvereine, auch über die Rolle der Wettbewerbe].<br />
                        •   [Anon.], „Correspondance“, in: <em>Revue et Gazette musicale de Paris</em> 19/27 (4. Juli 1852), S. 221f. [Ausführungen zu Chorwettbewerben in Belgien bzw. im internationalen Vergleich mit Frankreich und Deutschland].<br />
                        •   [Anon.], „Über die Preisconcurrenz bei Gesangfesten“, in: <em>Süddeutsche Musikzeitung</em> 1/15 (12. Juli 1852), S. 57f. [Plädoyer für die Abschaffung der Wettgesänge, da diese dem vereinigenden und auf Geselligkeit ausgerichteten Wesens des Männergesangs widersprächen].<br />
                        •   B-n., „Über das niederrheinische Gesangfest in Cleve“, in: <em>Niederrheinische Musik-Zeitung</em> 1/8 (20. August 1853), S. 62f. [auch allgemein zu deutschen Männergesangsfesten und zum Preissingen].<br />
                        •   Dz., „Schweizerbriefe“, in: <em>Neue Zeitschrift für Musik</em> 41/8 (18. August 1854), S. 81f. [Kritik an Verfahrensweisen der Männerchorwettbewerbe; vor allem an den Preisverleihungen und der Urteilsfindung der Jury].<br />
                        •   L.B., „Zur Geschichte des Männergesangs“, in: <em>Niederrheinische Musik-Zeitung</em> 3/35 (1. September 1855), S. 273f. [zu Männergesangsvereinen in Deutschland inkl. Gesangswettstreite, die hier jedoch „undeutsch“ genannt werden].<br />
                        •   [Anon.], „Allemagne“, in: <em>Le Guide musical</em> 2/14 (5. Juni 1856), S. 3 [Planung eines Wettbewerbs für Chorgesang durch M. Sachse in Hamburg].<br />
                        •   J. B. Rongé, „Les sociétés chorales en Belgique“, in: <em>Revue et Gazette musicale de Paris</em> 25/44 (31. Oktober 1858), S. 359-360 [Aufsatz zum belgischen Chorvereinswesen und seinen Wettbewerben].<br />
                        •   [Anon.], „Le Società corale nel Belgio“, in: <em>Gazzetta Musicale di Napoli</em> 8/8 (24. Februar 1859), S. 59f. [Bericht über belgische Gesangsvereinen und Chorwettbewerbe].<br />
                        •   Redaktion, „Návrh k stanovám“, in: <em>Dalibor</em> 5/14 (10. Mai 1862), S. 106, 5/15 (20. Mai 1862), S. 113 [Preisausschreiben des Gesangsvereins „Matice pěvecká“: Information zu Regularien und Preisen].<br />
                        •   [Anon.], „Aus der Schweiz“, in: <em>Süddeutsche Musikzeitung</em> 11/35 (1. September 1862), S. 139 [zu geplanten Reformen bei den Chorwettbewerben der eidgenössischen Gesangsfeste].<br />
                        •   [Anon.], „Kunstnotizen“, in: <em>Blätter für Musik, Theater und Kunst</em> 8/72 (5. September 1862), S. 288 [Eidgenössisches Sängerfest: Änderung der Statuten, v.a. im Hinblick auf die Profile der Teilwettbewerbe „Kunstgesang“ und „Volksgesang“].<br />
                        •   [Anon.], „Eine Stimme aus Frankreich über Musik- und Gesang-Vereine“, in: <em>Niederrheinische Musik-Zeitung</em> 10/40 (4. Oktober 1862), S. 318f. [Männergesangsvereine in Frankreich, inkl. Gesangswettbewerbe].<br />
                        •   [Anon.], „Allemagne“, in: <em>Le Guide musical</em> 8/35 (30. Oktober 1862), S. 139 [Dachverband der Gesangvereine in Deutschland organisiert alle 4 Jahre ein Festival und alle 2 Jahre einen Gesangswettbewerb].<br />
                        •   Camille de Vos, „Les Sociétés Chorales“, in: <em>La France musicale</em> 27/23 (7. Juni 1863), S. 173f. [zu Chorwettbewerben].<br />
                        •   Camille de Vos, „Les Sociétés Chorales“, in: <em>La France musicale</em> 26/26 (29. Juni 1862), S. 201 [zu Gesangs- und Orphéonwettbewerben].<br />
                        •   Camille de Vos, „Les Sociétés Chorales“, in: <em>La France musicale</em> 27/28 (12. Juli 1863), S. 213f. [zu Chorwettbewerben].<br />
                        •   [Anon.], „Dur und Moll“, in: <em>Signale für die musikalische Welt</em> 23/10 (3. Februar 1865), S. 154 [zu den Wettsingen bei den eidgenössischen Sängerfesten in der Schweiz].<br />
                        •   [Anon.], „Nachrichten“, in: <em>Neue Berliner Musikzeitung</em> 19/12 (22. März 1865), S. 95 [Anzahl von Gesangvereinen, Chorwettbewerben und Musikfesten in Frankreich].<br />
                        •   Blaise Lyon, „Le chant a première vue“, in: <em>L'Avenir musical</em> 2/6 (15. März 1866), S. 45ff. [zum Blattsingen bei Chorwettbewerben]<br />
                        •   Jean-Pierre, „Récit d'un campagnard“, in: <em>L'Avenir musical</em> 2/7 (1. April 1866), S. 49 ff. [Bericht eines Landbewohners über seine Erfahrungen im Gesangverein und bei Gesangswettbewerben].<br />
                        •   Blaize-Lyon, „La lecture e vue“, in: <em>L'Avenir musical</em> 2/10 (15. Mai 1866), S. 61 [zum Blattsingen bei Chorwettbewerben].<br />
                        •   Abel Pagès, „Du règlement“, in: <em>L'Avenir musical</em> 2/10 (15. Mai 1866), S. 62 [Reglementvorschläge zu Blattsingwettbewerben].<br />
                        •   G. Sylvain, „Règles de concours à vue“, in: <em>L'Avenir musical</em> 2/12 (15. Juni 1866), S. 70 [Regeln für Blattsingwettbewerbe].<br />
                        •   [Anon.], „Die Preis-Aufgaben des Rheinischen Sängervereins“, in: <em>Niederrheinische Musik-Zeitung</em> 14/27 (7. Juli 1866), S. 209f. [zu den Kompositionspreisausschreiben des Rheinischen Sängervereins / Vergleich zwischen Preisen für die Nachwuchsförderung und Preisen zur Förderung bestimmter musikalischer Gattungen].<br />
                        •   Abel Pagès, „Les programmes de lecture à vue“, in: <em>L'Avenir musical</em> 2/19 (1. Oktober 1866), S. 99 [zum Blattsingen bei Chorwettbewerben].<br />
                        •   Gustave Chouquet, „L'Orphéon“, in: <em>Le Ménestrel</em> 34/28 (9. Juni 1867), S. 219f. [Verweis auf „concours annuel de poésie et de musique chorale“ der Stadt Paris].<br />
                        •   [Anon.], „Scraps of Musical News“, in: <em>Western Musical World</em> 4/9 (September 1867), S. 133 [Preissingen finde bei nordamerikanischen Sängerfesten nicht statt, da diese Wettbewerbe ‚Unzufriedenheit‘ bei den TeilnehmerInnen auslösten.]<br />
                        •   Charles Rousselle, „Protestation“, in: <em>L'Avenir musical</em> 4/15 (15. Juni 1868), S. 263 [zur Verwendung neuer Notationssysteme bei Blattsingwettbewerben].<br />
                        •   [Anon.], „Our Amateurs“, in: <em>Dwight's Journal of Music</em> 29/22 (15. Januar 1870), S. 173 [u.a. zum deutschsprachigen Chorwesen und ihren Wettbewerben in den USA].</p>
                    <p id="line196"><b>Orphéons</b></p>
                    <p id="line198">•   Georges Bousquet, „Concours d'Orphéons et de musiques d'harmonie à Fontainebleau, le dimanche 19 juin“, in: <em>Revue et Gazette musicale de Paris</em> 20/26 (26. Juni 1853), S. 227f. [auch allgemeine Äußerungen zu Orphéon-Wettbewerben im Zusammenhang der Volksbildung].<br />
                        •   P. S., „Association des artistes musiciens de France. Assemblée générale annuelle“, in: <em>Revue et Gazette musicale de Paris</em> 24/14 (5. April 1857), S. 107f. [Abdruck des Berichts von Jean-Louis Le Bel mit Betonung der wichtigen Rolle der Association des artistes musiciens bei der Ausrichtung von Orphéon-Wettbewerben].<br />
                        •   Ém.-Mathieu de Monter, „Les orphéons du temps passé“, in: <em>Revue et Gazette musicale de Paris</em> 25/28 (11. Juli 1858), S. 229f., 25/30 (25. Juli 1858), S. 245-247, 25/33 (15. August 1858), S. 269f., 25/38 (19. September 1858), S. 309f. [zu Chorwettbewerben und ihren historischen Vorläufern].<br />
                        •   [Anon.], „Nouvelles“, in: <em>L'Art musical</em> 2/13 (27. Februar 1862), S. 103f. [zu Orphéon-Festen und -Wettbewerben].<br />
                        •   J.F. Vaudin, „Des jurys“, in: <em>L'Art musical</em> 2/17 (27. März 1862), S. 132f. [zu den Jurys bei Orphéon-Wettbewerben].<br />
                        •   Gamma, „Des concours orphéoniques“, in: <em>L'Art musical</em> 2/24 (15. Mai 1862), S. 188f.<br />
                        •   [Anon.], „France“, in: <em>Le Guide musical</em> 8/40 (20. November 1862), S. 161 [1862 gab es 24 Orpheón-Wettbewerbe in Frankreich; insgesamt 700 Musikvereine mit 19.240 Orphéonisten nahmen teil].<br />
                        •   Sextius Durand, „Les Concours d'Orphéons“, in: <em>La France musicale</em> 27/28 (12. Juli 1863), S. 215f. [zu Orphéon-Wettbewerben].<br />
                        •   [Anon.], „Nouvelles“, in: <em>Revue et Gazette musicale de Paris</em> 31/1 (3. Januar 1864), S. 7 [Bericht zu den Orphéon-Wettbewerben in Frankreich. Im Jahr 1863 fanden insgesamt 38 dieser Wettbewerbe statt].<br />
                        •   [Anon.], „France“, in: <em>Le Guide musical</em> 11/10 (9. März 1865), S. 43 [1864 gab es 58 Orphéon-Wettbewerbe in Frankreich; insgesamt 1.500 Musikvereine mit 60.000 Orphéonisten nahmen teil].<br />
                        •   [Anon.], „De l'organisation des concours“, in: <em>L'Avenir musical</em> 2/16 (15. August 1866), S. 87 [zur Organisation von Orphéon-Wettbewerben].<br />
                        •   J.-P. Moschelès, „A propos des concours“, in: <em>L'Avenir musical</em> 4/6 (15. März 1868), S. 239 [Bericht zu Orphéon-Wettbewerben].<br />
                        •   Th. de Lajarte, „Les sociétés chorales et instrumentales“, in: <em>Le Ménestrel</em> 35/43 (20. September 1868), S. 341f. [Auszug aus der Zeitung „La Patrie“: Artikel zur Orphéon-Bewegung, u.a. zur Rolle der Wettbewerbe im Blattlesen].<br />
                        •   Th. De Lajarte, „Les sociétés chorales et instrumentales“, in: <em>L'Avenir musical</em> 4/20 (15. Oktober 1868), S. 296 [zur Geschichte der Orphéon-Wettbewerbe in Frankreich].<br />
                        •   [Anon.], „De l'unité du jury“, in: <em>L'Avenir musical</em> 4/20 (15. Oktober 1868), S. 299 [zu Orphéon-Wettbewerben].<br />
                        •   Sylvain St-Étienne, „Les concours d'Orphéons“, in: <em>La France musicale</em> 34/17 (24. April 1870), S. 127f. [zu Orphéon-Wettbewerben].</p>
                    <p id="line216"><b>Blasmusik</b></p>
                    <p id="line218">•   [Anon.], „Gegenwärtiger Zustand der Musik in dem südlichen Theile des Königreichs der Niederlande“, in: <em>Allgemeine musikalische Zeitung</em> 25/49 (3. Dezember 1823), S. 803-809, hier 807f. [zu Blasmusikwettbewerben in Belgien].<br />
                        •   Fétis, „Deuxième lettre à M. Édouard Fétis. Sur l'état actuel de la musique dans la Belgique, et sur son avenir dans ce pays“, in: <em>Revue Musicale</em> 7/22 (29. Juni 1833), S. 169-172 [zu Blasmusikvereinen in Belgien und deren regelmäßigen Wettbewerben, die Fétis als nationales Phänomen beurteilt].<br />
                        •   A. de M..., „La musique en Belgique. Les concerts. – Les concours de musique.“, in: <em>Revue et Gazette musicale de Paris</em> 7/38 (31. Mai 1840), S. 320 [umfassend zu Wettbewerben belgischer Blasmusikvereine allgemein].<br />
                        •   A. S., „De Paris à Rome et de Rome à Paris. 20 mars 1841“, in: <em>Revue et Gazette musicale de Paris</em> 8/26 (1. April 1841), S. 201f. [zu Wettbewerben belgischer Blasmusikvereine].<br />
                        •   A. Elwart, „Projet relatif à l'organisation d'une chapelle-musique municipale de la ville de Paris“, in: <em>Revue et Gazette musicale</em> 13/23 (7. Juni 1846), S. 180f. [Entwurf zur Einrichtung einer städtisch-geistlichen Kapelle in Paris mit dem Plan der Ausrichtung eines jährlichen Preisausschreibens einer Messe].<br />
                        •   [Anon.], „Des Concours“, in: <em>La France musicale</em> 15/19 (11. Mai 1851), S. 147f. [zu Chor- und Blaskapellenwettbewerben, v. a. in Belgien und Deutschland].<br />
                        •   [Anon.], „Correspondance“, in: <em>Revue et Gazette musicale de Paris</em> 18/29 (20. Juli 1851), S. 239 [Allgemeine Ausführungen zum etablierten musikalischen Wettbewerbswesen in Belgien, bezogen auf Blaskapellen- und Chorwettbewerbe sowie diverse Preisausschreiben für Komposition].<br />
                        •   Th. De Lajarte, „Les Sociétés Chorales et Instrumentales“, in: <em>La France musicale</em> 32/38 (20. September 1868), S. 295f. [zu Gesangsvereinen und Blaskapellen und den entsprechenden Wettbewerben].</p>
                    <p id="line228"><b>Oper</b></p>
                    <p id="line230">•   [Anon.], „American Opera“, in: <em>Saroni’s Musical Times I</em> 46 (10. August 1850), S. 542 [Diskussion zu einem Preisausschreiben für eine amerikanische Oper].<br />
                        •   [Anon.], „Notizie Italiane“, in: <em>Boccherini</em> 3/11 (16. August 1864), S. 46 [Kritik am Opernkompositionswettbewerb Concorso della Pergola].<br />
                        •   [Anon.], „Notizie Italiane“, in: <em>Boccherini</em> 5/8 (10. Juli 1866), S. 59 [Änderungsvorschläge zum Opernkompositionswettbewerb Concorso della Pergola].</p>
                    <p id="line235"><b>Opernlibretti</b></p>
                    <p id="line237">•   [Anon.], „Die Anforderungen der Gegenwart an einen guten Operntext“, in: <em>Süddeutsche Musikzeitung</em> 2/32 (8. August 1853), S. 125f. 2/33 (15. August 1853), S. 129f., 2/34 (22. August 1853), S. 133f., 2/35 (29. August 1853), S. 137f., 2/36 (5. September 1853), S. 141f., 2/37 (12. September 1853), S. 145f., 2/38 (19. September 1853), S. 149f., 2/39 (26. September 1853), S. 153f., 2/40 (3. Oktober 1853), S. 157f. [Ausgangspunkt ist das Preisausschreiben für ein Opernlibretto, dessen Vorgaben hier reflektiert und präzisiert werden sollen].<br />
                        •   [Anon.], „Die blutige Nonne von Scribe und Gounod“, in: <em>Süddeutsche Musikzeitung</em> 3/45 (6. November 1854), S. 178 [Misslingen eines Preisausschreibens für ein Opernlibretto].<br />
                        •   [Anon.], „Noch ein Wort über das Preisausschreiben auf einen guten Opertext“, in: <em>Süddeutsche Musikzeitung</em> 3/46 (13. November 1854), S. 181 [Kommentar zum Misslingen des Preisausschreibens der Kanitz'schen Buchhandlung in Gera].<br />
                        •   Fétis père, „Que peut-on faire pour améliorer la condition des jeunes compositeurs et pour Porter remède à la décadence de la musique? (4e article) (1)“, in: <em>Revue et Gazette musicale de Paris</em> 25/11 (14. März 1858), S. 81-83 [Forderung nach einem staatlich geförderten Preisausschreiben und dessen Entwurf für Libretti und Komposition von Opern zur Aufführung an den Theatern von Lyon, Marseille, Bordeaux, Rouen und Straßburg, wobei sich der Kompositions-Teilwettbewerb an die Rompreisträger richten soll].<br />
                        •   W. Lackowitz, „Ein Blick auf die komische Oper“, in: <em>Süddeutsche Musikzeitung</em> 18/49 (6. Dezember 1869), S. 192f. [zu Preisausschreiben für Opernlibretti].</p>
                    <p id="line244"><b>Symphonien</b></p>
                    <p id="line246">•   Gottschalk Wedel [= Zuccalmaglio], „Die Preissymphonie 1“, in: <em>Neue Zeitschrift für Musik</em> 5/37 (4. November 1836), S. 147f.<br />
                        •   Die Redaction [= Robert Schumann], „Die Preissymphonie 2“, in: <em>Neue Zeitschrift für Musik</em> 5/38 (8. November 1838), S. 151f.<br />
                        •   G. W. Fink, „Die Preis-Symphonie von Franz Lachner“, in: <em>Allgemeine musikalische Zeitung</em> 39/13 (29. März 1837), S. 201-209, 39/14 (5. April 1837), S. 217-222.<br />
                        •   [Anon], „Académie royale de Belgique“, in: <em>Le Guide musical</em> 1/24 (9. August 1855), S. 1 [Planung eines Wettbewerbs für eine Sinfonie].<br />
                        •   [Justus], „One Thousand Florins for a Symphony. To the Editor of the Musical World“, in: <em>The Musical World</em> 35/7 (14. Februar 1857), S. 103 [Aufforderung an die Philharmonic Society, einen Preis für eine Sinfonie auszuschreiben].</p>
                    <p id="line253"><b>Kirchenmusik</b></p>
                    <p id="line255">•   H. J. Gauntlett, „The Gresham Prize“, in: <em>The Musical World</em> 2/19 (22. Juli 1836), S. 81f., 2/20 (29. Juli 1836), S. 97f.<br />
                        •   Fétis père, „Que peut-on faire pour améliorer la condition des jeunes compositeurs et pour Porter remède à la décadence de la musique! (3e article) (1)“, in: <em>Revue et Gazette musicale de Paris</em> 25/8 (21. Februar 1858), S. 57-59 [Forderung nach einem Preisausschreiben und dessen Entwurf für Kirchenmusik, um an einen geeigneten Kapellmeister einer reformierten Domkapelle zu kommen].<br />
                        •   [Anon.]: „Prizes for Church Music“, in: <em>The Orchestra</em> 11/282 (20. Februar 1869), S. 346 [zu Preisausschreiben im Kontext von Kirchenmusik].</p>
                    <p id="line260"><b>Weltausstellungen</b></p>
                    <p id="line262">•   [Anon.], „Faites divers“, in: <em>L'Art musical</em> 6/51 (22. November 1866), S. 408 [Ankündigung, dass es auf der Weltausstellung 1867 Chorwettbewerbe geben wird].<br />
                        •   [Anon.], „Nachrichten“, in: <em>Neue Berliner Musikzeitung</em> 21/8 (20. Februar 1867), S. 63 [zu den Vorbereitungen der Musikwettbewerbe rund um die Pariser Weltausstellung 1867].<br />
                        •   [Anon.], „Nachrichten“, in: <em>Neue Berliner Musikzeitung</em> 21/11 (13. März 1867), S. 87 [zu den Vorbereitungen der Chorwettbewerbe rund um die Pariser Weltausstellung 1867].<br />
                        •   [Anon.], „Pariser Briefe“, in: <em>Niederrheinische Musik-Zeitung</em> 15/13 (30. März 1867), S. 97f. [zu den musikalischen Aktivitäten (Preisausschreiben / Wettbewerbe und Konzerte) während der Pariser Weltausstellung 1867].<br />
                        •   H.E., „Die französische Weltausstellung und ihre Bedeutung für die Tonkunst“, in: <em>Neue Berliner Musikzeitung</em> 21/25 (19. Juni 1867), S. 194 [musikalische Wettbewerbe während der Weltausstellung 1867].<br />
                        •   Ralph, „La fête au palais de l'Industrie“, in: <em>L'Art musical</em> 7/31 (4. Juli 1867), S. 241f. [feierliche Preisverleihung (Ausstellung) mit musikalischer Untermalung auf der Weltausstellung 1867].<br />
                        •   [Anon.], „Faits divers“, in: <em>L'Art musical</em> 7/31 (4. Juli 1867), S. 247 [Preisträger Instrumentenbau auf der Weltausstellung 1867].<br />
                        •   [Anon.], „Faits divers“, in: <em>L'Art musical</em> 7/32 (11. Juli 1867), S. 255 [Liste der Preisträger der Kategorie Instrumentenbau bei der Weltausstellung 1867].<br />
                        •   M. de Pontécoulant, „La musique à l'Exposition universelle XIV“, in: <em>L'Art musical</em> 7/34 (25. Juli 1867), S. 265f. [Preisträger Instrumentenbau auf der Weltausstellung 1867].<br />
                        •   M. de Pontécoulant, „La musique à l'Exposition universelle XVI“, in: <em>L'Art musical</em> 7/36 (8. August 1867), S. 281f. [Klavierbau, Jury].<br />
                        •   [Anon.], „Zerstreute Betrachtungen über den Nutzen, welchen die Pariser Weltausstellung der Tonkunst gebracht hat“, in: <em>Neue Berliner Musikzeitung</em> 21/35 (28. August 1867), S. 276f. [musikalische Wettbewerbe während der Weltausstellung 1867].<br />
                        •   [Anon.], „Chronique musicale“, in: <em>L'Avenir musical</em> 3/10 (1. September 1867), S. 186 [Bericht zu den Orphéon-Wettbewerben der Pariser Weltausstellung 1867].<br />
                        •   M. de Pontécoulant, „La musique à l'Exposition universelle XXII“, in: <em>L'Art musical</em> 7/42 (19. September 1867), S. 329f. [Preisverleihung, Blasinstrumente].</p>
                    <p id="line277"><b>Florenz</b></p>
                    <p id="line279">• P. Sc., „Courier musical“, in: <em>L'Art musical</em> 2/26 (29. Mai 1862), S. 201f. [Bericht u.a. über die verschiedenen Musikvereine in Florenz, inkl. deren Preisausschreiben (Basevi u.a.)]<br />
                        •   J. d'Ortigue, „Concerts populaires à Florence“, in: <em>Le Ménestrel</em> 30/37 (16. August 1863), S. 296 [zur Pflege der Instrumentalmusik in Florenz; u.a. zu diversen Gesellschaften und ihren Kompositionswettbewerben].<br />
                        •   Giuseppe Mascia, „Osservazioni sul Concorso del Quartetto“, in: <em>Gazzetta Musicale di Napoli</em> 11/31 (16. August 1863), S. 121f. [Beobachtungen zum Concorso Basevi und Vergleich mit neapolitanischen Kompositionswettbewerben].<br />
                        •   Giuseppe Masela, Luigi Mazzone, „Osservazioni aggiunte su di un foglio pervenuto da Firenze intorno al Concorso del Quartetto“, in: <em>Gazzetta Musicale di Napoli</em> 11/39 (11. Oktober 1863), S. 158 [kritischer Bericht zum Concorso Basevi].</p>
                    <p id="line285"><b>Neapel</b></p>
                    <p id="line287">•   L. Mazzone, „Protesta“, in: <em>Gazzetta Musicale di Napoli</em> 12/17 (1. Mai 1864), S. 73f. [zu den Regularien der Preisausscheiben des „Circolo Artistico-Musicale Bonamici“].<br />
                        •   [Anon.], „Atti del Circolo Bonamici“, in: <em>Gazzetta Musicale di Napoli</em> 13/4 (9. Februar 1865), S. 4ff. [zu Preisausschreiben in Neapel].<br />
                        •   Luigi Mazzone, „Concorsi di composizione musicale“, in: <em>Gazzetta Musicale di Napoli</em> 13/5 (19. Februar 1865), S. 2f. [Regularien von Kompositionswettbewerben in Neapel].<br />
                        •   [Anon.], „Miscellanea“, in: <em>Gazzetta Musicale di Napoli</em> 13/17 (10. Juni 1865), S. 4 [der „Circolo Artistico-Musicale Bonamici“ entwirft ein Regelwerk zu Kompositions- und Instrumentalwettbewerben].<br />
                        •   F. Bonamici, M.C. Caputo, „Regolamento pe’Concorsi nel Circolo-Bonamici“, in: <em>Gazzetta Musicale di Napoli</em> 13/25 und 26 (17. September 1865), S. 7 [Regelwerk für Kompositions-, Performance- und Schulwettbewerbe des „Circolo Artistico-Musicale Bonamici“].</p>
                    <p id="line294"><b>Deutsche Tonhalle</b></p>
                    <p id="line296">•   [Anon.], „Nachrichten“, in: <em>Süddeutsche Musikzeitung</em> 2/17 (25. April 1853), S. 68 [Kassenbericht des Vereins „Deutsche Tonhalle Mannheim“ inkl. Ausgaben für Preise].<br />
                        •   [Anon.], „Deutsche Tonhalle“, in: <em>Niederrheinische Musik-Zeitung</em> 2/19 (13. Mai 1854), S. 150f. [Jahresbericht des Vereins „Deutsche Tonhalle Mannheim“ mit Angabe der Ein- und Ausgaben, inkl. der auf Preise verwendeten Gelder]<br />
                        •   [Anon.], „Einige Worte über die niederländische Gesellschaft zur Beförderung der Tonkunst verbunden mit einigen Worten an die Deutsche Tonhalle in Mannheim“, in: <em>Süddeutsche Musikzeitung</em> 5/2 (8. Januar 1856), S. 5f. [Kritik an der Tonhalle, die sich zu einseitig auf Preisausschreiben verlege, die angesichts der vielen Komponisten in Deutschland hier doch gar nicht nötig seien].<br />
                        •   Der Vereins-Vorstand, „Deutsche Tonhalle Mannheim“, in: <em>Niederrheinische Musik-Zeitung</em> 9/29 (20. Juli 1861), S. 231 [Jahresberichte des Vereins inkl. Preisausschreiben].<br />
                        •   Der Vereis-Vorstand, „Deutsche Tonhalle“, in: Süddeutsche Musikzeitung 10/30 (29. Juli 1861), S. 120 [Jahresbericht 1860 der Deutschen Tonhalle Mannheim inkl. Auflistung der Ausgaben für Preisausschreiben].</p>
                    <p id="line303"><b>Eisteddfod</b></p>
                    <p id="line305">•   Abel of Aberystwyth, „The Welsh Eisteddfod“, in: <em>The Musical World</em> 43/40 (7. Oktober 1865), S. 625 [Leserbrief zur Geschichte des Eisteddfod in Wales].<br />
                        •   [Musicus], „Welsh Grand National Eisteddfod“, in: <em>The Musical Standard</em> 7/164 (21. September 1867), S. 181f.</p>
                    <p id="line308"><b>Welsh Harp</b></p>
                    <p id="line310">•   Brinley Richards, „The Welsh Harp. To the Editor of the 'Musical World'“, in: <em>The Musical World</em> 47/12 (20. März 1869), S. 195 [Zur kulturellen Bewahrung der „Welsh Harp“ fordert der Verfasser dazu auf, Preise für das Harfenspiel auszuschreiben.].<br />
                        •   William Rees, „The Welsh Harp. To the Editor of the ‘Musical World’“, in: <em>The Musical World</em> 47(15 (10. April 1869), S. 248.<br />
                        •   [A Welshman], „The Welsh Harp. To the Editor of the ‘Musical World’“, in: <em>The Musical World</em> 47/23 (5. Juni 1869), S. 405.</p>
                    <p id="line315"><b>Niederländischer Verein zur Beförderung der Tonkunst</b></p>
                    <p id="line317">•   [Anon.], „Ueber die Wirksamkeit der holländischen Gesellschaft zur Beförderung der Tonkunst“, in: <em>Süddeutsche Musikzeitung</em> 5/51 (15. Dezember 1856), S. 201f. [Bericht von der Generalversammlung des Vereins inkl. Erwähnung von Preisausschreiben].<br />
                        •   L.B., „Der Verein zur Beförderung der Tonkunst in den Niederlanden“, in: <em>Niederrheinische Musik-Zeitung</em> 9/3 (19. Januar 1861), S. 21f. [Jahresbericht des Vereins inkl. Preisausschreiben].<br />
                        •   Dr. V., „Ueber die Wirksamkeit der niederländischen Societät zur Beförderung der Tonkunst während des Jahres 1860“, in: <em>Süddeutsche Musikzeitung</em> 10/7 (18. Februar 1861), S. 25 [Jahresbericht des niederländischen Vereins zur Beförderung der Tonkunst inkl. Preisausschreiben].</p>
                    <p id="line322"><b>Meyerbeers Erbe</b></p>
                    <p id="line324">•   [Anon.], „France“, in: <em>Le Guide musical</em> 10/27 (30. Juni / 7. Juli 1864), S. 109 [Nachlass Meyerbeers: der ‚Société des auteurs et compositeurs dramatiques‘ (Paris) 10.000 fr.; für ein Preisausschreiben in Paris 37.500 fr.; einer Krankenversicherung für MusikerInnen in Berlin 1.125 fr.].<br />
                        •   [Anon.], „Meyerbeer-Stipendium“, in: <em>Neue Berliner Musikzeitung</em> 18/25 (22. Juni 1864), S. 195 [zum Meyerbeer Kompositionsstipendium (inkl. Testament-Text Giacomo Meyerbeers)].<br />
                        •   [Anon.], „Bestimmungen Meyerbeer's über seine Stiftung für Tonkünstler“, in: <em>Niederrheinische Musik-Zeitung</em> 12/30 (23. Juli 1864), S. 239 [zu Meyerbeers Stiftung mit Stipendienvergabe].</p>
                    <p id="line329"><b>Mozart-Stiftung</b></p>
                    <p id="line331">•   Der Verwaltungs-Ausschuss der Mozart-Stiftung, „Die Mozart-Stiftung in Frankfurt am Main“, in: <em>Niederrheinische Musik-Zeitung</em> 9/46 (16. November 1861), S. 365 [zur Mozart-Stiftung; auch zu den Karrieren ehemaliger und derzeitiger Stipendiaten].<br />
                        •   Prof. L. Bischoff, „Die Mozart-Stiftung in Frankfurt am Main“, in: <em>Niederrheinische Musik-Zeitung</em> 11/28 (11. Juli 1863), S. 217f. [Überblick über die Geschichte der Mozart-Stiftung].<br />
                        •   Dr. Bonfick, Dr. Eckhard, „27. Jahresbericht des Verwaltungs-Ausschusses der Mozart-Stiftung“, in: <em>Niederrheinische Musik-Zeitung</em> 13/46 (18. November 1865), S. 365f.</p>
                    <p id="line336"><b>Vögel</b></p>
                    <p id="line338">•   [Anon.], „Causeries musicales“, in: <em>Le Ménestrel</em> 17/27 (2. Juni 1850), o. S. [Detaillierter Bericht über jährliche Wettbewerbe des Gesangs von Buchfinken in Belgien].<br />
                        •   [Anon.], „o. T. “, in: <em>The Orchestra</em> 7/180 (18. Juli 1868), S. 265 [zu Vogelgesangswettbewerben in Nordfrankreich und Belgien].</p>
                    <p id="line342"><b>Diverses</b></p>
                    <p id="line344">•   [Anon.], „Discours prononcé par M. Fétis, comme directeur de la classe des beaux-arts de l'Académie royale de Belgique“, in: <em>Revue et Gazette musicale de Paris</em> 19/39 (26. September 1852), S. 322f.  [Bericht Fétis zur jährlichen Sitzung der Brüsseler Classe des Beaux-Arts, in dem er unter anderem auf die Rolle staatlicher Akademien bei musikalischen Preisausschreiben eingeht].<br />
                        •   [Anon.], „Correspondance“, in: <em>Revue et Gazette musicale de Paris</em> 21/6 (5. Februar 1854), S. 45f. [Bemerkung über Förderung des Musiklebens durch den belgischen Staat u. a. durch Kompositions-Preisausschreiben].<br />
                        •   [Anon.], „La cornemuse en Angleterre“, in: <em>Le Ménestrel</em> 21/50 (12. November 1854), S. 3 [jährliche Dudelsackwettbewerbe eines schottischen Musikvereins].<br />
                        •   [Anon.], „Prize Songs“, in: <em>Dwight’s Journal of Music</em> 8/26 (29. März 1856, S. 204 [kritische Auseinandersetzung mit musikalischen Preisausschreiben in den USA].<br />
                        •   Bischoff, „Der Mozart-Verein“, in: <em>Niederrheinische Musik-Zeitung</em> 4/29 (19. Juli 1856), S. 232f. [zum Mozart-Verein, inkl. der von ihm ausgeschrieben Preise/Stipendien].<br />
                        •   [Anon.], „Società Russa di musica“, in: <em>Gazzetta Musicale di Napoli</em> 8/26 (14. Juli 1859), S. 181 [Gründung des russischen Musikfördervereins am 1. Mai 1859; u. a. wird ein jährlicher Kompositionspreis ausgeschrieben].<br />
                        •   [Anon.], „The True Duty of Amateurs”, in: <em>The Musical Standard</em> 1/16 (16. März 1863), S. 217-219 [zu musizierenden Laien und Preisausschreiben].<br />
                        •   [Anon.], „The Rossini Prize“, in: <em>Dwight’s Journal of Music</em> 28/21 (2. Januar 1869), S. 371 [zum geplanten Rossini-Preis in Frankreich].<br />
                        •   [Anon.], „Kunstnotizen“, in: <em>Blätter für Musik, Theater und Kunst</em> 16/51 (28. Juni 1870), S. 182 [„Pianoforte-Wettrennen“ in Cedar Rapids (Iowa): Anscheinend handelt es sich hierbei um ein Klavier-Duell, bei dem es um die Schnelligkeit des Vortrags ging].</p>

                </div>
                </Layout>
            </Content>
        </Layout>
    );
} 

